# Generated by Django 3.0.7 on 2020-07-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
