# Generated by Django 3.0.7 on 2020-07-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
