# Generated by Django 3.0.7 on 2020-07-19 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
