# Generated by Django 3.0.7 on 2020-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_auto_20200719_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('rubrica', models.FileField(blank=True, null=True, upload_to='documentos/rubricas')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
