# Generated by Django 3.0.7 on 2020-07-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_rubrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='rubrica',
            field=models.FileField(blank=True, null=True, upload_to='rubricas/'),
        ),
    ]
