# Generated by Django 3.0.7 on 2020-07-20 01:54

import cursos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_auto_20200719_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='rubrica',
            field=models.FileField(blank=True, null=True, upload_to='rubricas/', validators=[cursos.validators.validate_file_extension]),
        ),
    ]
