# Generated by Django 3.0.7 on 2020-07-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_auto_20200719_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='comentario',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
