# Generated by Django 3.0.7 on 2020-07-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
