# Generated by Django 3.0.7 on 2020-07-20 01:50

import cursos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', validators=[cursos.validators.validate_file_extension]),
        ),
    ]
