# Generated by Django 3.1 on 2020-09-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_auto_20200719_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
