# Generated by Django 3.1.1 on 2020-09-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_auto_20200919_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='MDocumento',
        ),
        migrations.RenameModel(
            old_name='Rubrica',
            new_name='MRubrica',
        ),
    ]
