# Generated by Django 3.1.1 on 2020-09-20 02:23

import cursos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_auto_20200919_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdocumento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[cursos.validators.validate_file_extension]),
        ),
    ]
