# Generated by Django 3.1.1 on 2020-10-31 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0026_auto_20201030_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='nota',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
