# Generated by Django 3.1.1 on 2020-10-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0029_auto_20201031_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='upload_At',
        ),
    ]
