# Generated by Django 3.1.1 on 2020-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0032_tarea_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
    ]
