# Generated by Django 3.1.1 on 2020-11-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0033_auto_20201031_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='exigencia',
            field=models.IntegerField(verbose_name='Exigencia'),
        ),
    ]
