# Generated by Django 3.1.1 on 2020-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0034_auto_20201101_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='promedio',
            field=models.IntegerField(default='0', verbose_name='Promedio'),
        ),
    ]
