# Generated by Django 3.1.1 on 2020-11-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0035_tarea_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='promedio',
            field=models.IntegerField(default=0, verbose_name='Promedio'),
        ),
    ]
