# Generated by Django 3.1.1 on 2020-11-04 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0036_auto_20201103_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nota',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70)], verbose_name='Nota'),
        ),
    ]
