# Generated by Django 3.1.1 on 2020-11-04 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0037_auto_20201104_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nota',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='promedio',
            field=models.FloatField(default=0, verbose_name='Promedio'),
        ),
    ]
