# Generated by Django 3.1.1 on 2020-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0039_auto_20201104_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
    ]
