# Generated by Django 3.1.1 on 2020-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0040_auto_20201104_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmarActa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
