# Generated by Django 3.1.4 on 2020-12-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0043_auto_20201204_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='actafirmas',
            name='Alumno',
            field=models.CharField(default="Nombre", max_length=50),
        ),
        migrations.AddField(
            model_name='actafirmas',
            name='Rut_Alumno',
            field=models.CharField(default="11111111-1", max_length=50),
        ),
    ]
