# Generated by Django 3.1.4 on 2020-12-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0044_auto_20201205_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actafirmas',
            name='Alumno',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='actafirmas',
            name='Rut_Alumno',
            field=models.CharField(default=11111110, max_length=50),
        ),
    ]
