# Generated by Django 3.1.4 on 2020-12-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0045_auto_20201205_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actafirmas',
            name='Alumno',
        ),
        migrations.RemoveField(
            model_name='actafirmas',
            name='Rut_Alumno',
        ),
    ]
